### ISSUE TITLE
Build Environment instructions missing python-click package

### ISSUE THREAD

**Issue by derekbelrose** [blend-os/docs#5]
The instructions here: https://docs.blendos.co/docs/build-blend/build_environment#installing-required-packages require 'python-click' to be included or `assemble` will not run correctly.

```
Traceback (most recent call last):
  File "/usr/local/bin/assemble", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

Patch forthcoming.

**Comment by Ast3risk-ops** [comment]
Source has moved, do not make PRs here.

**Comment by Ast3risk-ops** [comment]
@derekbelrose I will implement your PR soon on the new repo at

https://git.blendos.co/blendos/docs

**Comment by Ast3risk-ops** [comment]
https://git.blendos.co/blendOS/docs/-/commit/de9ba659fdcf159ceee5fd037475a5b6498ba811
